### ISSUE TITLE
Error log while starting the gateway

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/product-microgateway#1070]
### Description:

``` java
java.lang.RuntimeException: java.io.FileNotFoundException: getConfig (The system cannot find the file specified)
        at com.moandjiezana.toml.Toml.read(Toml.java:74)
        at org.wso2.micro.gateway.tools.GetConfig.getConfigurations(GetConfig.java:25)
        at org.wso2.micro.gateway.tools.Main.main(Main.java:12)
Caused by: java.io.FileNotFoundException: getConfig (The system cannot find the file specified)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at com.moandjiezana.toml.Toml.read(Toml.java:72)
        ... 2 more
The system cannot find the batch label specified - isMetricsEnabled
Error while reading observability configurations from the file
```
### Affected Product Version:

3.1.0 beta

### Environment details (with versions):
- OS: windows 10
- Client:
- Env (Docker/K8s):

---

**Comment by praminda** [comment]
I believe this happens only on windows Please provide the environment details properly. If that is the case this is a duplicate of #1107

**Comment by praminda** [comment]
Duplicate of #1107

**Comment by AmaliMatharaarachchi** [comment]
@praminda yes. it was in windows. Closing the issue as it was duplicated in #1107
