### ISSUE TITLE
Analytics : java.io.EOFException occurs when file upload method is enabled.

### ISSUE THREAD

**Issue by VirajSalaka** [wso2/product-microgateway#1138]
### Description:
When the analytics event publishing is done via the file-upload method and start a load test, the following error is visible in the analytics node intermittently. Hence, the data inside that file is not processed by the analytics node.
```
[2020-03-13 15:12:26,317] ERROR {org.wso2.extension.siddhi.io.mgwfile.MGWFileDataRetriever} - Error occurred while reading the API Usage file. java.io.EOFException: Unexpected end of ZLIB input stream
	at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:240)
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
	at java.util.zip.ZipInputStream.read(ZipInputStream.java:194)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.io.BufferedReader.readLine(BufferedReader.java:324)
	at java.io.BufferedReader.readLine(BufferedReader.java:389)
	at org.wso2.extension.siddhi.io.mgwfile.MGWFileDataRetriever.publishEvents(MGWFileDataRetriever.java:91)
	at org.wso2.extension.siddhi.io.mgwfile.MGWFileDataRetriever.run(MGWFileDataRetriever.java:57)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
This occurs when the rotating period parameter and the uploading time span period paramter is set to the same value. (or rather close values).

And in the gateway log, we can see the following log messages.
```
2020-03-13 16:20:58,437 INFO  [wso2/gateway/src/gateway/utils] - [Utils] [-] File compressed successfully 
2020-03-13 16:20:58,442 INFO  [wso2/gateway/src/gateway/utils] - [Utils] [-] Existing file deleted successfully 
2020-03-13 16:20:58,444 INFO  [wso2/gateway/src/gateway/utils] - [RotateTimerTask] [-] File rotated successfully. 
2020-03-13 16:21:07,024 INFO  [wso2/gateway/src/gateway/utils] - [UploadTimerTask] [-] Successfully uploaded the file: api-usage-data.dat.1584096656032.baa2d260-8790-4624-9dc6-f9decd188f4f.zip 
2020-03-13 16:21:56,062 INFO  [wso2/gateway/src/gateway/utils] - [UploadTimerTask] [-] Successfully uploaded the file: api-usage-data.dat.1584096716029.b272e01c-ce81-486f-b15b-53f72325c67d.zip 
2020-03-13 16:21:57,585 INFO  [wso2/gateway/src/gateway/utils] - [Utils] [-] File compressed successfully 
2020-03-13 16:21:57,609 INFO  [wso2/gateway/src/gateway/utils] - [Utils] [-] Existing file deleted successfully 
2020-03-13 16:21:57,609 INFO  [wso2/gateway/src/gateway/utils] - [RotateTimerTask] [-] File rotated successfully. 
```
Probably this behavior can be explained as this.

- When the file rotating task starts, it will create the file. But to complete the rotation, it takes some amount of time.
- Before the rotation is completed, the gateway uploads the file to the analytics node. Therefore it results a corrupted file in analytics node. 

The solution we could try.

- When the file rotation happens, we should have a different file name and that file should not be uploaded to the analytics node. The after the rotation is completed, we should rename the file and the gateway should send only those kinds of files.

### Steps to reproduce:
Set the **uploadingTimeSpanInMillis** and **rotatingPeriod** to 60000. And enable analytics using file-upload method. Then start a load test which will take to run 4-5 mins.

### Affected Product Version:
3.1.0-beta

### Environment details (with versions):
- OS: MacOS Mojave
- Client:
- Env (Docker/K8s):

---
#### Suggested Labels:
Affected/3.1.0-beta

**Comment by VirajSalaka** [comment]
Working on this.
