### ISSUE TITLE
Distributed Throttling is not working.

### ISSUE THREAD

**Issue by VirajSalaka** [wso2/product-microgateway#1148]
### Description:
When distributed throttling is enabled, the requests do not thottle out.
In the Traffic Manager, we can see the following log.
```
[2020-03-18 13:07:03,530] ERROR - FunctionExecutor Exception on execution plan 'requestPreProcessorExecutionPlan' on class 'org.wso2.siddhi.extension.map.CreateFromJSONFunctionExtension', Cannot create JSON from '' in create from json function
org.wso2.siddhi.core.exception.ExecutionPlanRuntimeException: Cannot create JSON from '' in create from json function
at org.wso2.siddhi.extension.map.CreateFromJSONFunctionExtension.execute(CreateFromJSONFunctionExtension.java:65) ~[siddhi-extension-map_3.2.6.jar:?]
at org.wso2.siddhi.core.executor.function.FunctionExecutor.execute(FunctionExecutor.java:94) [siddhi-core_3.2.6.jar:?]
at org.wso2.siddhi.core.executor.function.FunctionExecutor.execute(FunctionExecutor.java:98) [siddhi-core_3.2.6.jar:?]
at org.wso2.siddhi.core.query.selector.attribute.processor.AttributeProcessor.process(AttributeProcessor.java:38) [siddhi-core_3.2.6.jar:?]
at org.wso2.siddhi.core.query.selector.QuerySelector.processNoGroupBy(QuerySelector.java:103) [siddhi-core_3.2.6.jar:?]
at org.wso2.siddhi.core.query.selector.QuerySelector.process(QuerySelector.java:86) [siddhi-core_3.2.6.jar:?]
at org.wso2.siddhi.core.query.input.ProcessStreamReceiver.processAndClear(ProcessStreamReceiver.java:178) [siddhi-core_3.2.6.jar:?]
at org.wso2.siddhi.core.query.input.ProcessStreamReceiver.process(ProcessStreamReceiver.java:88) [siddhi-core_3.2.6.jar:?]
at org.wso2.siddhi.core.query.input.ProcessStreamReceiver.receive(ProcessStreamReceiver.java:174) [siddhi-core_3.2.6.jar:?]
at org.wso2.siddhi.core.stream.StreamJunction.sendData(StreamJunction.java:219) [siddhi-core_3.2.6.jar:?]
at org.wso2.siddhi.core.stream.StreamJunction.access$200(StreamJunction.java:47) [siddhi-core_3.2.6.jar:?]
at org.wso2.siddhi.core.stream.StreamJunction$Publisher.send(StreamJunction.java:348) [siddhi-core_3.2.6.jar:?]
at org.wso2.siddhi.core.stream.input.InputDistributor.send(InputDistributor.java:49) [siddhi-core_3.2.6.jar:?]
```
The reason behind this was that the event contains an empty field called properties. But the Traffic Manager expects it to be a json. So the solution would be setting that property to an empty json.

### Steps to reproduce:
Enable distributed throttling and invoke the gateway.

### Affected Product Version:
3.1.0-beta

### Environment details (with versions):
- OS: MacOS Mojave
- Client:
- Env (Docker/K8s):
- API Manager - 3.1.0-rc1

---
#### Suggested Labels:
Affected/3.1.0-beta

**Comment by VirajSalaka** [comment]
https://github.com/wso2/product-microgateway/blob/e9227999398ebb59d121703dd7722f5b741a2e8b/components/micro-gateway-core/src/main/ballerina/src/gateway/filters/throttle_filter.bal#L378

Change this to properties.toJsonString()
