### ISSUE TITLE
An error pops up when building a project, if the name of the file, which is used to save API definition, contains space for  API definition 3.0.1.

### ISSUE THREAD

**Issue by tharmini** [wso2/product-microgateway#1292]
### Description:
An error pops up when building a project, if the name of the file, which is used to save API definition, contains space for  API definition 3.0.1

### Steps to reproduce:
1. Save an API definition with swagger (2).json or openapi (2).yaml file name(file name with space).
2. Build the project in MGW
sample API definition can find from [link](https://drive.google.com/file/d/1srbbbzvCQduHkvgHV-WUL0uzCPgq5CpF/view?usp=sharing
)

### Affected Product Version:
MGW 3.2.0 alpha
<img width="737" alt="Screen Shot 2020-06-19 at 12 27 49 PM" src="https://user-images.githubusercontent.com/29250881/85105586-556f1280-b228-11ea-97f5-2e3806c05ebd.png">

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by tharmini** [comment]
OpenAPIV3Parser library does not support the above version OpenAPI definition  3.0.0.

**Comment by praminda** [comment]
@menakaj 
Tried to import an API (PizzaShackAPI) and build the project. Following error is printed in toolkit log file. When debugging I noticed opeAPI is returned as null from [this line](https://github.com/wso2/product-microgateway/pull/1347/files#diff-78fa0ca820d3c1942a0f6574606e7cd4R101)

```
[2020-07-27 07:38:36,145] ERROR {org.wso2.apimgt.gateway.cli.cmd.Main} - Internal error occurred while executing command.
java.lang.NullPointerException
        at org.wso2.apimgt.gateway.cli.utils.OpenAPICodegenUtils.validateAPINameAndVersion(OpenAPICodegenUtils.java:960)
        at org.wso2.apimgt.gateway.cli.utils.OpenAPICodegenUtils.validateOpenAPIDefinition(OpenAPICodegenUtils.java:976)
        at org.wso2.apimgt.gateway.cli.codegen.CodeGenerator.lambda$null$1(CodeGenerator.java:108)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
        at org.wso2.apimgt.gateway.cli.codegen.CodeGenerator.lambda$generate$2(CodeGenerator.java:98)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at org.wso2.apimgt.gateway.cli.codegen.CodeGenerator.generate(CodeGenerator.java:92)
        at org.wso2.apimgt.gateway.cli.cmd.BuildCmd.execute(BuildCmd.java:162)
        at java.util.Optional.ifPresent(Optional.java:159)
        at org.wso2.apimgt.gateway.cli.cmd.Main.main(Main.java:50)
```

**Comment by menakaj** [comment]
The issue is with the server URI used in the API definition. 
SwaggerV3Parser validates the server uri. It should be in valid format. (http/s://<host>:<port>/
