### ISSUE TITLE
Adapter kills and runs to a crash loop back loop 

### ISSUE THREAD

**Issue by mpmunasinghe** [wso2/product-microgateway#1771]
### Description:
In a situation where an API is missing an endpoint configuration adapter fails to continue the sync. This also results in a crash loop back for adapter since the main program crashes. The error should be handled gracefully and continue the adapter startup. 

```
2021-03-25 13:11:33 INFO [server.go:417] - [xds.UpdateEnforcerApis] [-] New cache update for the label: Production and Sandbox version: 378221271
panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 1 [running]:
github.com/wso2/micro-gw/internal/api.extractAPIInformation(0xc000a58000, 0x1fc0, 0x3e00, 0xc000a58000, 0x1fc0, 0x3e00, 0x0, 0x0, 0x2000, 0x7f09812f8000, ...)
	/build/jenkins-home/workspace/products/product-microgateway_envoy-gw/target/checkout/adapter/internal/api/apis_impl.go:235 +0x679
github.com/wso2/micro-gw/internal/api.extractAPIProject(0xc0009de000, 0x1418, 0x1e00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/build/jenkins-home/workspace/products/product-microgateway_envoy-gw/target/checkout/adapter/internal/api/apis_impl.go:125 +0xb58
github.com/wso2/micro-gw/internal/api.ApplyAPIProject(0xc0009de000, 0x1418, 0x1e00, 0xc0006aa8e0, 0x1, 0x1, 0x0, 0x0)
	/build/jenkins-home/workspace/products/product-microgateway_envoy-gw/target/checkout/adapter/internal/api/apis_impl.go:159 +0x5d
github.com/wso2/micro-gw/internal/synchronizer.PushAPIProjects(0xc000c22000, 0x20a98, 0x3fe00, 0xc0006aa8e0, 0x1, 0x1, 0x0, 0x0)
	/build/jenkins-home/workspace/products/product-microgateway_envoy-gw/target/checkout/adapter/internal/synchronizer/apis_fetcher.go:198 +0x2b9
github.com/wso2/micro-gw/internal/mgw.fetchAPIsOnStartUp(0xc000252480)
	/build/jenkins-home/workspace/products/product-microgateway_envoy-gw/target/checkout/adapter/internal/mgw/mgw.go:273 +0x5d4
github.com/wso2/micro-gw/internal/mgw.Run(0xc000252480)
	/build/jenkins-home/workspace/products/product-microgateway_envoy-gw/target/checkout/adapter/internal/mgw/mgw.go:216 +0x23cf
main.startMicroGateway(0xc00003c1b0, 0x1, 0x1)
	/build/jenkins-home/workspace/products/product-microgateway_envoy-gw/target/checkout/adapter/cmd/microgateway/main.go:57 +0x105
main.main()
	/build/jenkins-home/workspace/products/product-microgateway_envoy-gw/target/checkout/adapter/cmd/microgateway/main.go:37 +0x5a 
```

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s): K8S

---
#### Suggested Labels:
Choreo

**Comment by pubudu538** [comment]
This is already fixed.
