### ISSUE TITLE
Subscription/Application throttling does not work and block the request path.

### ISSUE THREAD

**Issue by VirajSalaka** [wso2/product-microgateway#1802]
### Description:
Subscription/Application throttling does not work with newly added policies. Resulting in the following error.

```
enforcer_1  | java.lang.NullPointerException
enforcer_1  | 	at org.wso2.micro.gateway.enforcer.security.KeyValidator.validate(KeyValidator.java:254)
enforcer_1  | 	at org.wso2.micro.gateway.enforcer.security.KeyValidator.validateSubscriptionDetails(KeyValidator.java:202)
enforcer_1  | 	at org.wso2.micro.gateway.enforcer.security.KeyValidator.validateSubscriptionDetails(KeyValidator.java:143)
enforcer_1  | 	at org.wso2.micro.gateway.enforcer.security.KeyValidator.validateSubscription(KeyValidator.java:61)
enforcer_1  | 	at org.wso2.micro.gateway.enforcer.security.jwt.JWTAuthenticator.validateSubscriptionUsingKeyManager(JWTAuthenticator.java:353)
enforcer_1  | 	at org.wso2.micro.gateway.enforcer.security.jwt.JWTAuthenticator.validateSubscriptionUsingKeyManager(JWTAuthenticator.java:341)
enforcer_1  | 	at org.wso2.micro.gateway.enforcer.security.jwt.JWTAuthenticator.authenticate(JWTAuthenticator.java:138)
enforcer_1  | 	at org.wso2.micro.gateway.enforcer.security.AuthFilter.authenticate(AuthFilter.java:119)
enforcer_1  | 	at org.wso2.micro.gateway.enforcer.security.AuthFilter.handleRequest(AuthFilter.java:105)
enforcer_1  | 	at org.wso2.micro.gateway.enforcer.api.API.executeFilterChain(API.java:41)
enforcer_1  | 	at org.wso2.micro.gateway.enforcer.api.RestAPI.process(RestAPI.java:97)
enforcer_1  | 	at org.wso2.micro.gateway.enforcer.server.RequestHandler.process(RequestHandler.java:59)
enforcer_1  | 	at org.wso2.micro.gateway.enforcer.grpc.ExtAuthService.check(ExtAuthService.java:50)
enforcer_1  | 	at io.envoyproxy.envoy.service.auth.v3.AuthorizationGrpc$MethodHandlers.invoke(AuthorizationGrpc.java:245)
enforcer_1  | 	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:180)
enforcer_1  | 	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331)
enforcer_1  | 	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:814)
enforcer_1  | 	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
enforcer_1  | 	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
enforcer_1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
enforcer_1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
enforcer_1  | 	at java.base/java.lang.Thread.run(Unknown Source)
```

The cause is the the subscription policy is not updated in the datastore. Hence when the subpolicy extracted from data store it remains null. And afterwards, the microgateway is executing method on the null object. 

### Steps to reproduce:

Create a subscription policy.
Assign to a subscription.
Generate a token
And invoke.

### Affected Product Version:
m10-snapshot

### Environment details (with versions):
- OS: 
- Client:
- Env (Docker/K8s): Docker-with-apim setup with throttling, eventhub and subscription enabled.

---

**Comment by VirajSalaka** [comment]
Same Behavior observed with the newly added application policies as well.
