### ISSUE TITLE
Analytics event publishing does not work when token from /testKey endpoint is used.

### ISSUE THREAD

**Issue by VirajSalaka** [wso2/product-microgateway#1882]
### Description:
$subject. Following error log is visible.

```
enforcer_1  | [Cloud-Analytics-Queue-Worker-pool-2-thread-1] ERROR org.wso2.am.analytics.publisher.reporter.cloud.ParallelQueueWorker - Builder instance is not duly filled. Event building failed
enforcer_1  | org.wso2.am.analytics.publisher.exception.MetricReportingException: apiName is missing in metric data. This metric event will not be processed further.
enforcer_1  | 	at org.wso2.am.analytics.publisher.reporter.cloud.DefaultResponseMetricEventBuilder.validate(DefaultResponseMetricEventBuilder.java:59)
enforcer_1  | 	at org.wso2.am.analytics.publisher.reporter.AbstractMetricEventBuilder.build(AbstractMetricEventBuilder.java:32)
enforcer_1  | 	at org.wso2.am.analytics.publisher.reporter.cloud.ParallelQueueWorker.run(ParallelQueueWorker.java:56)
enforcer_1  | 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
enforcer_1  | 	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
enforcer_1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
enforcer_1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
enforcer_1  | 	at java.base/java.lang.Thread.run(Unknown Source)

```

### Steps to reproduce:
Enable analytics with a valid analytics_token and a valid analytics_authURL
Get a token from /testKey endpoint
Invoke the API 

### Affected Product Version:
choreo-connect 0.9.0-alpha

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s): docker-compose Choreo-connect distribution

---

**Comment by VirajSalaka** [comment]
Closing the issue as it is already fixed.
