### ISSUE TITLE
Handling cert validation failures 

### ISSUE THREAD

**Issue by mpmunasinghe** [wso2/product-microgateway#2239]
### Description:

With a cert file updated with an extra newline following cert validation error is thrown in the enforcer. Although the server continued to start due to this certificate not being valid token validation started failing. Hence we should trim the certs when parsing and in cases of failure the failure should reflect in the health of the pod accordingly. 

> [2021-09-27 13:03:59,902][] ERROR - {org.wso2.choreo.connect.enforcer.util.TLSUtils} - Error while adding certificates to the truststore.
java.security.cert.CertificateException: Could not parse certificate: java.io.IOException: Empty input
	at sun.security.provider.X509Factory.engineGenerateCertificate(Unknown Source) ~[?:?]
	at java.security.cert.CertificateFactory.generateCertificate(Unknown Source) ~[?:?]
	at org.wso2.choreo.connect.enforcer.util.TLSUtils.getCertsFromFile(TLSUtils.java:123) ~[org.wso2.choreo.connect.enforcer-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
	at org.wso2.choreo.connect.enforcer.util.TLSUtils.updateTruststoreWithMutlipleCertPem(TLSUtils.java:133) ~[org.wso2.choreo.connect.enforcer-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
	at org.wso2.choreo.connect.enforcer.util.TLSUtils.lambda$addCertsToTruststore$1(TLSUtils.java:102) ~[org.wso2.choreo.connect.enforcer-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) [?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) [?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) [?:?]
	at java.util.Iterator.forEachRemaining(Unknown Source) [?:?]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source) [?:?]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) [?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) [?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) [?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) [?:?]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) [?:?]
	at java.util.stream.ReferencePipeline.forEach(Unknown Source) [?:?]
	at org.wso2.choreo.connect.enforcer.util.TLSUtils.addCertsToTruststore(TLSUtils.java:101) [org.wso2.choreo.connect.enforcer-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
	at org.wso2.choreo.connect.enforcer.config.ConfigHolder.loadTrustStore(ConfigHolder.java:310) [org.wso2.choreo.connect.enforcer-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
	at org.wso2.choreo.connect.enforcer.config.ConfigHolder.<init>(ConfigHolder.java:100) [org.wso2.choreo.connect.enforcer-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
	at org.wso2.choreo.connect.enforcer.config.ConfigHolder.getInstance(ConfigHolder.java:108) [org.wso2.choreo.connect.enforcer-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
	at org.wso2.choreo.connect.enforcer.server.AuthServer.main(AuthServer.java:67) [org.wso2.choreo.connect.enforcer-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
Caused by: java.io.IOException: Empty input
	... 21 more

### Steps to reproduce:
update a truststore certificate with a certificate file with an additional newline at end. Use an token which is validated agains the said certificate endpoint. 

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by VirajSalaka** [comment]
+1 for both tasks.
1. This is the location where the certs are read. In here, the enforcer reads the file and assign the inputstream straightaway. Rather than doing that, first the file should be read and trimmed the newline character. After that it should generate the inputstream and proceed.
https://github.com/wso2/product-microgateway/blob/aa26df596365de3e16e5c84b6a5c5e4301435392/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/util/TLSUtils.java#L123
2. Shall we panic the enforcer or should we just let the health check fail in case of certificate read failure.?
@pubudu538 @mpmunasinghe @menakaj

**Comment by pubudu538** [comment]
As this is a util method, we should throw the exception and let the caller handle the situation. If it the startup, we can panic the enforcer. But in other cases, we should not do that.
