### ISSUE TITLE
Analytics publishing doesn't work with azure tracing

### ISSUE THREAD

**Issue by praminda** [wso2/product-microgateway#2259]
### Description:

Enforcer throws below error
```
Exception in thread "main" java.lang.NoSuchMethodError: 'reactor.core.publisher.Flux reactor.core.publisher.Flux.retryWhen(java.util.function.Function)'
	at com.azure.core.amqp.implementation.RetryUtil.withRetry(RetryUtil.java:58)
	at com.azure.core.amqp.implementation.ReactorConnection.getClaimsBasedSecurityNode(ReactorConnection.java:142)
	at com.azure.messaging.eventhubs.implementation.EventHubReactorAmqpConnection.createSession(EventHubReactorAmqpConnection.java:150)
	at com.azure.core.amqp.implementation.ReactorConnection.lambda$createSession$5(ReactorConnection.java:200)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(Unknown Source)
	at com.azure.core.amqp.implementation.ReactorConnection.lambda$createSession$6(ReactorConnection.java:194)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:113)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1815)
	at reactor.core.publisher.MonoCallable.subscribe(MonoCallable.java:61)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1815)
	at com.azure.core.amqp.implementation.AmqpChannelProcessor.subscribe(AmqpChannelProcessor.java:229)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4046)
	at reactor.core.publisher.Mono.block(Mono.java:1726)
	at com.azure.messaging.eventhubs.EventHubProducerClient.createBatch(EventHubProducerClient.java:126)
	at org.wso2.am.analytics.publisher.client.EventHubClient.createProducerWithRetry(EventHubClient.java:106)
	at org.wso2.am.analytics.publisher.client.EventHubClient.<init>(EventHubClient.java:81)
	at org.wso2.am.analytics.publisher.reporter.cloud.DefaultAnalyticsMetricReporter.<init>(DefaultAnalyticsMetricReporter.java:63)
	at org.wso2.am.analytics.publisher.reporter.MetricReporterFactory.createMetricReporter(MetricReporterFactory.java:51)
	at org.wso2.carbon.apimgt.common.analytics.publishers.impl.AnalyticsDataPublisher.initialize(AnalyticsDataPublisher.java:60)
	at org.wso2.carbon.apimgt.common.analytics.AnalyticsServiceReferenceHolder.setConfigurations(AnalyticsServiceReferenceHolder.java:46)
	at org.wso2.choreo.connect.enforcer.analytics.DefaultAnalyticsEventPublisher.init(DefaultAnalyticsEventPublisher.java:117)
	at org.wso2.choreo.connect.enforcer.analytics.AnalyticsFilter.<init>(AnalyticsFilter.java:76)
	at org.wso2.choreo.connect.enforcer.analytics.AnalyticsFilter.getInstance(AnalyticsFilter.java:84)
	at org.wso2.choreo.connect.enforcer.analytics.AccessLoggingService.init(AccessLoggingService.java:58)
	at org.wso2.choreo.connect.enforcer.server.AuthServer.main(AuthServer.java:96)
```

There seems to be a dependency conflict between azure monitor dependencies and analytics publishing dependencies.
### Steps to reproduce:
- Enabled analytics and azure tracing
- Run the setup
### Affected Product Version:

1.0.0-m1
### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s): all

**Comment by praminda** [comment]
This has happened due to a dependency version conflict in  `am.publisher.client` and `azure.exporter`'s reactor dependencies.
