### ISSUE TITLE
Error for Open API v3 APIs 

### ISSUE THREAD

**Issue by pubudu538** [wso2/product-microgateway#231]
**Description:**

When setting up the project for OpenAPI v3 APIs, getting the following error. The issue comes as we validate Swagger definition using the Swagger Parser. Swagger parser library which we have used does not support for Open API v3. The latest released library supports that and we need to uplift the version. 

https://github.com/swagger-api/swagger-parser/tree/v2.0.2)

[2018-08-28 13:09:43,875] ERROR {org.wso2.apimgt.gateway.cli.cmd.Main} - Internal error occurred while executing command. 
java.lang.NullPointerException
	at org.wso2.apimgt.gateway.cli.model.template.service.BallerinaService.buildContext(BallerinaService.java:67)
	at org.wso2.apimgt.gateway.cli.model.template.service.BallerinaService.buildContext(BallerinaService.java:82)
	at org.wso2.apimgt.gateway.cli.codegen.CodeGenerator.generate(CodeGenerator.java:66)
	at org.wso2.apimgt.gateway.cli.cmd.SetupCmd.execute(SetupCmd.java:296)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.wso2.apimgt.gateway.cli.cmd.Main.main(Main.java:50)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by praminda** [comment]
This should get fixed after the latest set of improvements we've planned for the cli toolkit. Should be ready in 2.7.0-m2

**Comment by VirajSalaka** [comment]
Previously, microgateway was only compatible with swagger version 2. Along with the restructuring commands process, support for OpenAPI version 3 will be added.

**Comment by praminda** [comment]
@VirajSalaka thanks for the update.
Issue will be fixed by the planned solution for https://github.com/wso2/product-microgateway/issues/325
