### ISSUE TITLE
Can't invoke API using sandbox token

### ISSUE THREAD

**Issue by praminda** [wso2/product-microgateway#2355]
### Description:

When invoking an API using a sandbox token I get below error and I can see below error log in the enforcer.

**response:** 
`{"message":"Unclassified Validation Failure","description":"Error during validating the request","code":"102500"}`

**log:**
```
enforcer_1  | io.grpc.internal.SerializingExecutor run
enforcer_1  | SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed@55820187
enforcer_1  | java.lang.NullPointerException
enforcer_1  | 	at org.wso2.choreo.connect.enforcer.security.jwt.JWTAuthenticator.authenticate(JWTAuthenticator.java:232)
enforcer_1  | 	at org.wso2.choreo.connect.enforcer.security.AuthFilter.authenticate(AuthFilter.java:152)
enforcer_1  | 	at org.wso2.choreo.connect.enforcer.security.AuthFilter.handleRequest(AuthFilter.java:131)
enforcer_1  | 	at org.wso2.choreo.connect.enforcer.api.API.executeFilterChain(API.java:42)
enforcer_1  | 	at org.wso2.choreo.connect.enforcer.api.RestAPI.process(RestAPI.java:191)
enforcer_1  | 	at org.wso2.choreo.connect.enforcer.server.HttpRequestHandler.process(HttpRequestHandler.java:57)
enforcer_1  | 	at org.wso2.choreo.connect.enforcer.grpc.ExtAuthService.check(ExtAuthService.java:73)
enforcer_1  | 	at io.envoyproxy.envoy.service.auth.v3.AuthorizationGrpc$MethodHandlers.invoke(AuthorizationGrpc.java:245)
enforcer_1  | 	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:180)
enforcer_1  | 	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331)
enforcer_1  | 	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:814)
enforcer_1  | 	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
enforcer_1  | 	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
enforcer_1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
enforcer_1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
enforcer_1  | 	at java.base/java.lang.Thread.run(Unknown Source)
```
### Steps to reproduce:
1. Deploy pizzashack API from APIM
2. Add a sandbox API
3. Subscribe and generate sandbox keys
4. Invoke the API using sandbox token

### Affected Product Version:

1.0.0-alpha-snapshot
### Environment details (with versions):
- OS: Linux
- Client: curl
- Env (Docker/K8s): docker

**Comment by pubudu538** [comment]
Same stack trace can be seen for having a custom auth header.

**Comment by pubudu538** [comment]
Looks like a bug in APIM. When we generate a CK/CS in devportal, we get those keys as sandbox keys. Should be fixed in the wum updated pack.
