### ISSUE TITLE
Test cases failure intermittently. 

### ISSUE THREAD

**Issue by NipunaPrashan** [wso2/product-microgateway#254]
**Description:**
When building the source code, it fails to pass some test cases. The issue is; running tests are not waiting until the mocker server starts with the port 9443.

Error:

```
// Start Running AuthenticationFailureTestCase ...

2018-10-04 11:19:54 INFO  ServerInstance:370 - Extracting micro-gw zip file.. 
2018-10-04 11:19:59 INFO  ServerInstance:170 - Server Home /home/prashan/workspace/vick/microgateway/git/product-microgateway/tests/target/micro-gwtmp1538632194901/wso2am-micro-gw-2.6.1-SNAPSHOT
2018-10-04 11:19:59 INFO  Utils:142 - Port 9443 is closed and available for use
2018-10-04 11:19:59 INFO  CLIExecutor:48 - CLI Project Home: /home/prashan/workspace/vick/microgateway/git/product-microgateway/tests/target/userProject6452329164422217581
2018-10-04 11:19:59 INFO  CLIExecutor:51 - CLI Home: /home/prashan/workspace/vick/microgateway/git/product-microgateway/tests/target/micro-gwtmp1538632194901/wso2am-micro-gw-2.6.1-SNAPSHOT
micro-gw: Error occurred while trying to connect with server. Is the server running at https://localhost:9443?
2018-10-04 11:19:59 ERROR Main:61 - Error occurred while communicate with DCR endpoint: https://localhost:9443/client-registration/v0.14/register
org.wso2.apimgt.gateway.cli.exception.CLIRuntimeException: Error occurred while communicate with DCR endpoint: https://localhost:9443/client-registration/v0.14/register
        at org.wso2.apimgt.gateway.cli.oauth.OAuthServiceImpl.generateClientIdAndSecret(OAuthServiceImpl.java:145)
        at org.wso2.apimgt.gateway.cli.cmd.SetupCmd.execute(SetupCmd.java:261)
        at java.util.Optional.ifPresent(Optional.java:159)
        at org.wso2.apimgt.gateway.cli.cmd.Main.main(Main.java:50)
        at org.wso2.micro.gateway.tests.common.CLIExecutor.generate(CLIExecutor.java:61)
        at org.wso2.micro.gateway.tests.common.BaseTestCase.init(BaseTestCase.java:65)
        at org.wso2.micro.gateway.tests.services.AuthenticationFailureTestCase.setup(AuthenticationFailureTestCase.java:75)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
        at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
        at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:451)
        at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
        at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
        at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:163)
        at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)
        at org.testng.TestRunner.privateRun(TestRunner.java:648)
        at org.testng.TestRunner.run(TestRunner.java:505)
        at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
        at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
        at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
        at org.testng.SuiteRunner.run(SuiteRunner.java:364)
        at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
        at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
        at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
        at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
        at org.testng.TestNG.runSuites(TestNG.java:1028)
        at org.testng.TestNG.run(TestNG.java:996)
        at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
        at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
        at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
        at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1316)
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1291)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:250)
        at org.wso2.apimgt.gateway.cli.oauth.OAuthServiceImpl.generateClientIdAndSecret(OAuthServiceImpl.java:120)
        ... 35 more
```

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by hasuniea** [comment]
fixing the issue from https://github.com/wso2/product-microgateway/pull/338/
