### ISSUE TITLE
Error log for OPA policies with GET request when analytics enabled

### ISSUE THREAD

**Issue by slahirucd7** [wso2/product-microgateway#2771]
### Description:
Getting below error log for OPA policies when analytics enabled with a get request.

### Steps to reproduce:

1. Create an API with OPA policies added to a GET operation and deploy.
2. Enable analytics in Choreo-Connect
3. Invoke the API. 
4. Below log appears in Choreo Connect.

```


choreo-connect-with-apim-enforcer-1  | [2022-03-23 07:19:02,728][4b0ba5db-a07b-4f62-bf6a-3af2283bcb68][OPA, example.com, /t/example.com/opa/1.0.0] ERROR - {org.wso2.choreo.connect.enforcer.interceptor.MediationPolicyFilter} - OPA validation failed for the request: /t/example.com/opa/1.0.0/* [severity:Minor error_code:6101]
choreo-connect-with-apim-enforcer-1  | Mar 23, 2022 7:19:02 AM io.grpc.internal.SerializingExecutor run
choreo-connect-with-apim-enforcer-1  | SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed@37eb4496
choreo-connect-with-apim-enforcer-1  | java.lang.NullPointerException
choreo-connect-with-apim-enforcer-1  | 	at org.wso2.carbon.apimgt.common.analytics.collectors.impl.fault.AbstractFaultDataCollector.processRequest(AbstractFaultDataCollector.java:53)
choreo-connect-with-apim-enforcer-1  | 	at org.wso2.carbon.apimgt.common.analytics.collectors.impl.fault.AuthFaultDataCollector.collectFaultData(AuthFaultDataCollector.java:51)
choreo-connect-with-apim-enforcer-1  | 	at org.wso2.carbon.apimgt.common.analytics.collectors.impl.FaultyRequestDataCollector.collectData(FaultyRequestDataCollector.java:63)
choreo-connect-with-apim-enforcer-1  | 	at org.wso2.carbon.apimgt.common.analytics.collectors.impl.GenericRequestDataCollector.collectData(GenericRequestDataCollector.java:49)
choreo-connect-with-apim-enforcer-1  | 	at org.wso2.choreo.connect.enforcer.analytics.AnalyticsFilter.handleFailureRequest(AnalyticsFilter.java:214)
choreo-connect-with-apim-enforcer-1  | 	at org.wso2.choreo.connect.enforcer.api.RestAPI.process(RestAPI.java:232)
choreo-connect-with-apim-enforcer-1  | 	at org.wso2.choreo.connect.enforcer.server.HttpRequestHandler.process(HttpRequestHandler.java:64)
choreo-connect-with-apim-enforcer-1  | 	at org.wso2.choreo.connect.enforcer.grpc.ExtAuthService.check(ExtAuthService.java:80)
choreo-connect-with-apim-enforcer-1  | 	at io.envoyproxy.envoy.service.auth.v3.AuthorizationGrpc$MethodHandlers.invoke(AuthorizationGrpc.java:245)
choreo-connect-with-apim-enforcer-1  | 	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:180)
choreo-connect-with-apim-enforcer-1  | 	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
choreo-connect-with-apim-enforcer-1  | 	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
choreo-connect-with-apim-enforcer-1  | 	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
choreo-connect-with-apim-enforcer-1  | 	at io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86)
choreo-connect-with-apim-enforcer-1  | 	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331)
choreo-connect-with-apim-enforcer-1  | 	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:814)
choreo-connect-with-apim-enforcer-1  | 	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
choreo-connect-with-apim-enforcer-1  | 	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
choreo-connect-with-apim-enforcer-1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
choreo-connect-with-apim-enforcer-1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
choreo-connect-with-apim-enforcer-1  | 	at java.base/java.lang.Thread.run(Unknown Source)
choreo-connect-with-apim-enforcer-1  | 

```

### Affected Product Version:
Chreo-Connect-1.1.0-alpha2

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by pubudu538** [comment]
@Amila-Rukshan is working on this

**Comment by Amila-Rukshan** [comment]
I tried to recreate the issue when a request is valid or invalid with OPA policy but could not get the NullPointerException

**Comment by pubudu538** [comment]
@renuka-fernando will check this further.
