### ISSUE TITLE
[websocket] io.grpc.StatusRuntimeException and NPE thrown when closing a connection

### ISSUE THREAD

**Issue by suksw** [wso2/product-microgateway#2797]
### Description:
The following gets thrown when a websocket client sends a close frame and closes its connection while the server also gracefully closes.

```
[docker-java-stream--1464580521] INFO Enforcer - STDOUT: [2022-03-25 09:57:36,460][][] ERROR - {org.wso2.choreo.connect.enforcer.websocket.WebSocketResponseObserver} - websocket frame service onError: io.grpc.StatusRuntimeException: CANCELLED: cancelled before receiving half close [severity:Default error_code:0]
[docker-java-stream--1464580521] INFO Enforcer - STDERR: Mar 25, 2022 9:57:36 AM io.grpc.internal.SerializingExecutor run
[docker-java-stream--1464580521] INFO Enforcer - STDERR: SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1Closed@15cc9a5f
[docker-java-stream--1464580521] INFO Enforcer - STDERR: java.lang.NullPointerException
[docker-java-stream--1464580521] INFO Enforcer - STDERR: 	at java.base/java.util.concurrent.ConcurrentHashMap.containsValue(Unknown Source)
[docker-java-stream--1464580521] INFO Enforcer - STDERR: 	at java.base/java.util.concurrent.ConcurrentHashMap.contains(Unknown Source)
[docker-java-stream--1464580521] INFO Enforcer - STDERR: 	at org.wso2.choreo.connect.enforcer.grpc.WebSocketFrameService.removeObserver(WebSocketFrameService.java:51)
[docker-java-stream--1464580521] INFO Enforcer - STDERR: 	at org.wso2.choreo.connect.enforcer.websocket.WebSocketResponseObserver.onError(WebSocketResponseObserver.java:131)
[docker-java-stream--1464580521] INFO Enforcer - STDERR: 	at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onCancel(ServerCalls.java:270)
[docker-java-stream--1464580521] INFO Enforcer - STDERR: 	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.closedInternal(ServerCallImpl.java:353)
[docker-java-stream--1464580521] INFO Enforcer - STDERR: 	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.closed(ServerCallImpl.java:341)
[docker-java-stream--1464580521] INFO Enforcer - STDERR: 	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1Closed.runInContext(ServerImpl.java:861)
[docker-java-stream--1464580521] INFO Enforcer - STDERR: 	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
[docker-java-stream--1464580521] INFO Enforcer - STDERR: 	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
[docker-java-stream--1464580521] INFO Enforcer - STDERR: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[docker-java-stream--1464580521] INFO Enforcer - STDERR: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[docker-java-stream--1464580521] INFO Enforcer - STDERR: 	at java.base/java.lang.Thread.run(Unknown Source)
```

### Affected Product Version:
CC 1.1.0 beta

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by suksw** [comment]
Following is the only stack trace available for the initial `StatusRuntimeException: CANCELLED: cancelled before receiving half close` error 
```
[docker-java-stream-461454053] INFO Enforcer - STDOUT: [2022-03-26 08:58:02,704][][] ERROR - {org.wso2.choreo.connect.enforcer.websocket.WebSocketResponseObserver} - [io.grpc.Status.asRuntimeException(Status.java:524), io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onCancel(ServerCalls.java:273), io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.closedInternal(ServerCallImpl.java:353), io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.closed(ServerCallImpl.java:341), io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1Closed.runInContext(ServerImpl.java:861), io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37), io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123), java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.base/java.lang.Thread.run(Unknown Source)] [severity:Default error_code:0]
```
