### ISSUE TITLE
Error log from JWT validator

### ISSUE THREAD

**Issue by slahirucd7** [wso2/product-microgateway#2817]
### Description:
When doing the performance test with large number of tokens (1000) and when starting to 
send requests there are below error logs in enforcer.

<img width="1277" alt="image" src="https://user-images.githubusercontent.com/40932779/160533593-b02a9324-ceff-46c7-8147-d056ecfe1257.png">

---

<img width="1277" alt="image" src="https://user-images.githubusercontent.com/40932779/160533617-85560bc4-e287-4d99-8cf3-8d50572e1514.png">

---

<img width="950" alt="image" src="https://user-images.githubusercontent.com/40932779/160533693-8c34ca34-a14c-4ea9-9feb-f87188a2e4a2.png">

### Steps to reproduce:

1. Generate large number of tokens (1000).
2. Start to send requests considering large number of users users from above tokens.
3. Error logs appear from enforcer side (during the startup this happens).

### Affected Product Version:
Choreo-Connect-1.1.0-beta

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by renuka-fernando** [comment]
Textual form of the error log

```log
Mar 28, 2022 8:14:02 AM io.grpc.internal.SerializingExecutor run
SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed@2fc53b0c
java.lang.NullPointerException
        at org.wso2.choreo.connect.enforcer.security.jwt.validator.JWTValidator.getConsumerKey(JWTValidator.java:169)
        at org.wso2.choreo.connect.enforcer.security.jwt.validator.JWTValidator.validateToken(JWTValidator.java:92)
        at org.wso2.choreo.connect.enforcer.security.jwt.validator.JWTValidator.validateJWTToken(JWTValidator.java:74)
        at org.wso2.choreo.connect.enforcer.security.jwt.JWTAuthenticator.getJwtValidationInfo(JWTAuthenticator.java:559)
        at org.wso2.choreo.connect.enforcer.security.jwt.JWTAuthenticator.authenticate(JWTAuthenticator.java:186)
        at org.wso2.choreo.connect.enforcer.security.AuthFilter.authenticate(AuthFilter.java:163)
        at org.wso2.choreo.connect.enforcer.security.AuthFilter.handleRequest(AuthFilter.java:141)
        at org.wso2.choreo.connect.enforcer.api.API.executeFilterChain(API.java:42)
        at org.wso2.choreo.connect.enforcer.api.RestAPI.process(RestAPI.java:192)
        at org.wso2.choreo.connect.enforcer.server.HttpRequestHandler.process(HttpRequestHandler.java:64)
        at org.wso2.choreo.connect.enforcer.grpc.ExtAuthService.check(ExtAuthService.java:80)
        at io.envoyproxy.envoy.service.auth.v3.AuthorizationGrpc$MethodHandlers.invoke(AuthorizationGrpc.java:245)
        at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:180)
        at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
        at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
        at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
        at io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331)
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:814)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
```
