### ISSUE TITLE
Choreo Connect does not start in Windows 10 with Docker WSL

### ISSUE THREAD

**Issue by pubudu538** [wso2/product-microgateway#2918]
### Description:
The enforcer fails systematically in Exited status, and reporting the following error :
docker logs choreo-connect_enforcer_1
java.lang.IllegalArgumentException: Illegal base64 character a
        at java.base/java.util.Base64$Decoder.decode0(Unknown Source)
        at java.base/java.util.Base64$Decoder.decode(Unknown Source)
        at java.base/java.util.Base64$Decoder.decode(Unknown Source)
        at org.wso2.choreo.connect.enforcer.util.JWTUtils.getPrivateKey(JWTUtils.java:166)
        at org.wso2.choreo.connect.enforcer.util.FilterUtils.createClientKeyStore(FilterUtils.java:155)
        at org.wso2.choreo.connect.enforcer.config.ConfigHolder.loadOpaClientKeyStore(ConfigHolder.java:355)
        at org.wso2.choreo.connect.enforcer.config.ConfigHolder.<init>(ConfigHolder.java:110)
        at org.wso2.choreo.connect.enforcer.config.ConfigHolder.getInstance(ConfigHolder.java:118)
        at org.wso2.choreo.connect.enforcer.server.AuthServer.main(AuthServer.java:75)

### Environment details (with versions):
- OS: Windows/ Docker WSL
- Client:
- Env (Docker/K8s):

---

**Comment by nandulaperera** [comment]
**Suggested Fix :**

Removing this [code segment](https://github.com/wso2/product-microgateway/blob/main/enforcer-parent/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/util/JWTUtils.java#L158-L160) will resolve the issue.

This [fix](https://github.com/wso2/product-microgateway/commit/e0dadbd26b7540ceed45b5fcd0c12502464ad8da#diff-18d6bb9c148fc48381cdfd664636ce9c6b22a40fbce4df435dcec303552534a5R158-R160) was applied, as there was an issue with the line separator, when running the enforcer on WSL2 (in the dev environment).

After running the Choreo Connect 1.1.0 distribution on Windows 10 along with Docker Desktop and WSL2, it identifies the OS as WSL and the line separator as `\n`. But due to the above line separator replacement, the line separator is updated as `\r\n` and hence it will not replace the line separators in the private key.
