### ISSUE TITLE
[1.1.0][CC] - Scope claim parsing issue

### ISSUE THREAD

**Issue by sajith-madhusanka** [wso2/product-microgateway#3057]
### Description

It fails to parse the scope claim when it is presented as the string array as below,

"scope" : [ "scope1", "scope2" ]

### Steps to Reproduce

- Modified the APIM token issuer to include the scope claim as a string array (Please refer to the attached patch diff: [token_issuer.patch.txt](https://github.com/wso2/product-microgateway/files/9487362/token_issuer.patch.txt))

- Configured the APIM as the token service.
```
[[enforcer.security.tokenService]]
  name = "Resident Key Manager"
  issuer = "https://localhost:9443/oauth2/token"
  certificateAlias = "NDZjNDU4YzZkNjY5MzA0ODc4NjdhZTFhMjg2NGJmMmJhMjM5NGMyMjE1OTk5MDI0YzA2ZjExYjUzNDkwOGJlNw_RS256"
  jwksURL = ""
  validateSubscription = false
  consumerKeyClaim = "azp"
  certificateFilePath = "/home/wso2/security/truststore/apimpublic.pem"
```

- Deployed the choreo connect and invoked the API using the JWT token generated from the APIM.

### Version

1.1.0

### Relevant Log Output

```shell
[2022-09-02 18:27:39,665][22a9e428-a177-43c6-9354-632828919caa][] DEBUG - {org.wso2.choreo.connect.enforcer.api.APIFactory} - Looking for matching API with basepath: /v2 and version: 1.0.6 []
        enforcer_1  | [2022-09-02 18:27:39,665][22a9e428-a177-43c6-9354-632828919caa][] DEBUG - {org.wso2.choreo.connect.enforcer.server.RequestHandler} - API /v2/1.0.6 found in the cache []
        enforcer_1  | [2022-09-02 18:27:39,666][22a9e428-a177-43c6-9354-632828919caa][SwaggerPetstore, carbon.super, /v2] DEBUG - {org.wso2.choreo.connect.enforcer.cors.CorsFilter} - Cors Filter (enforcer) is applied. []
        enforcer_1  | [2022-09-02 18:28:16,445][22a9e428-a177-43c6-9354-632828919caa][SwaggerPetstore, carbon.super, /v2] DEBUG - {org.wso2.choreo.connect.enforcer.security.jwt.validator.JWTValidator} - Retrieve certificate from Token issuer and validating []
        enforcer_1  | [2022-09-02 18:28:55,343][22a9e428-a177-43c6-9354-632828919caa][SwaggerPetstore, carbon.super, /v2] ERROR - {org.wso2.choreo.connect.enforcer.security.jwt.JWTAuthenticator} - JWT Validation failed [severity:Default error_code:0]
        enforcer_1  | org.wso2.choreo.connect.enforcer.commons.exception.EnforcerException: Error while parsing JWT
        enforcer_1  |   at org.wso2.choreo.connect.enforcer.security.jwt.validator.JWTValidator.validateToken(JWTValidator.java:104) ~[org.wso2.choreo.connect.enforcer-1.1.0.jar:1.1.0]
        enforcer_1  |   at org.wso2.choreo.connect.enforcer.security.jwt.validator.JWTValidator.validateJWTToken(JWTValidator.java:68) ~[org.wso2.choreo.connect.enforcer-1.1.0.jar:1.1.0]
        enforcer_1  |   at org.wso2.choreo.connect.enforcer.security.jwt.JWTAuthenticator.getJwtValidationInfo(JWTAuthenticator.java:570) [org.wso2.choreo.connect.enforcer-1.1.0.jar:1.1.0]
        enforcer_1  |   at org.wso2.choreo.connect.enforcer.security.jwt.JWTAuthenticator.authenticate(JWTAuthenticator.java:186) [org.wso2.choreo.connect.enforcer-1.1.0.jar:1.1.0]
        enforcer_1  |   at org.wso2.choreo.connect.enforcer.security.AuthFilter.authenticate(AuthFilter.java:163) [org.wso2.choreo.connect.enforcer-1.1.0.jar:1.1.0]
        enforcer_1  |   at org.wso2.choreo.connect.enforcer.security.AuthFilter.handleRequest(AuthFilter.java:141) [org.wso2.choreo.connect.enforcer-1.1.0.jar:1.1.0]
        enforcer_1  |   at org.wso2.choreo.connect.enforcer.api.API.executeFilterChain(API.java:42) [org.wso2.choreo.connect.enforcer-1.1.0.jar:1.1.0]
        enforcer_1  |   at org.wso2.choreo.connect.enforcer.api.RestAPI.process(RestAPI.java:192) [org.wso2.choreo.connect.enforcer-1.1.0.jar:1.1.0]
        enforcer_1  |   at org.wso2.choreo.connect.enforcer.server.HttpRequestHandler.process(HttpRequestHandler.java:64) [org.wso2.choreo.connect.enforcer-1.1.0.jar:1.1.0]
        enforcer_1  |   at org.wso2.choreo.connect.enforcer.grpc.ExtAuthService.check(ExtAuthService.java:80) [org.wso2.choreo.connect.enforcer-1.1.0.jar:1.1.0]
        enforcer_1  |   at io.envoyproxy.envoy.service.auth.v3.AuthorizationGrpc$MethodHandlers.invoke(AuthorizationGrpc.java:245) [org.wso2.choreo.connect.enforcer-1.1.0.jar:1.1.0]
        enforcer_1  |   at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:180) [org.wso2.choreo.connect.enforcer-1.1.0.jar:1.1.0]
        enforcer_1  |   at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35) [org.wso2.choreo.connect.enforcer-1.1.0.jar:1.1.0]
        enforcer_1  |   at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23) [org.wso2.choreo.connect.enforcer-1.1.0.jar:1.1.0]
        enforcer_1  |   at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40) [org.wso2.choreo.connect.enforcer-1.1.0.jar:1.1.0]
        enforcer_1  |   at io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86) [org.wso2.choreo.connect.enforcer-1.1.0.jar:1.1.0]
        enforcer_1  |   at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331) [org.wso2.choreo.connect.enforcer-1.1.0.jar:1.1.0]
        enforcer_1  |   at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:814) [org.wso2.choreo.connect.enforcer-1.1.0.jar:1.1.0]
        enforcer_1  |   at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [org.wso2.choreo.connect.enforcer-1.1.0.jar:1.1.0]
        enforcer_1  |   at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [org.wso2.choreo.connect.enforcer-1.1.0.jar:1.1.0]
        enforcer_1  |   at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
        enforcer_1  |   at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
        enforcer_1  |   at java.lang.Thread.run(Unknown Source) [?:?]
        enforcer_1  | Caused by: java.text.ParseException: The "scope" claim is not a String
        enforcer_1  |   at com.nimbusds.jwt.JWTClaimsSet.getStringClaim(JWTClaimsSet.java:485) ~[org.wso2.choreo.connect.enforcer-1.1.0.jar:1.1.0]
        enforcer_1  |   at org.wso2.choreo.connect.enforcer.security.jwt.validator.JWTValidator.createJWTValidationInfoFromJWT(JWTValidator.java:171) ~[org.wso2.choreo.connect.enforcer-1.1.0.jar:1.1.0]
        enforcer_1  |   at org.wso2.choreo.connect.enforcer.security.jwt.validator.JWTValidator.validateToken(JWTValidator.java:89) ~[org.wso2.choreo.connect.enforcer-1.1.0.jar:1.1.0]
        enforcer_1  |   ... 22 more
        enforcer_1  | [2022-09-02 18:28:55,348][22a9e428-a177-43c6-9354-632828919caa][SwaggerPetstore, carbon.super, /v2] ERROR - {org.wso2.choreo.connect.enforcer.security.AuthFilter} - None of the authenticators were able to authenticate the request: /v2/pet/1 [severity:Minor error_code:6600]
```

**Comment by suksw** [comment]
Hi, please note that it will not be possible to release this before the most likely date. This will take at least till Friday. An issue  occurred in the pipeline related to increase in memory in our test suite, which has not happened before. This was not expected.  We are looking ways to permanently fix the pipeline.
