### ISSUE TITLE
Support having consumer key under the AUD claim as an array.

### ISSUE THREAD

**Issue by VirajSalaka** [wso2/product-microgateway#3247]
### Description

There are tokens which include the consumer key inside an array under the aud claim. In such scenarios, the choreo connect would result in the following error in the enforcer. 

```
Caused by: java.text.ParseException: The "aud" claim is not a String
enforcer_1  | 	at com.nimbusds.jwt.JWTClaimsSet.getStringClaim(JWTClaimsSet.java:485) ~[org.wso2.choreo.connect.enforcer-1.0.0.jar:1.0.0]
enforcer_1  | 	at org.wso2.carbon.apimgt.common.gateway.jwttransformer.DefaultJWTTransformer.getTransformedConsumerKey(DefaultJWTTransformer.java:50) ~[org.wso2.choreo.connect.enforcer-1.0.0.jar:1.0.0]
enforcer_1  | 	at org.wso2.choreo.connect.enforcer.security.jwt.validator.JWTValidator.getConsumerKey(JWTValidator.java:169) ~[org.wso2.choreo.connect.enforcer-1.0.0.jar:1.0.0]
enforcer_1  | 	at org.wso2.choreo.connect.enforcer.security.jwt.validator.JWTValidator.validateToken(JWTValidator.java:92) ~[org.wso2.choreo.connect.enforcer-1.0.0.jar:1.0.0]
enforcer_1  | 	... 22 more
```

### Steps to Reproduce

Start choreo-connect-with-apim setup.
Setup forgerock keymanager from the admin portal.
Create application and generate keys and subscribe to an API
Try invoking the API using a token obtained from the key manager.

### Version

1.0.0

### Relevant Log Output

```shell
enforcer_1  | [2023-02-07 13:54:29,236][6ec8ae0d-17d2-40f7-b8fc-af3b5a64050e] ERROR - {org.wso2.choreo.connect.enforcer.security.jwt.JWTAuthenticator} - JWT Validation failed
enforcer_1  | org.wso2.choreo.connect.enforcer.exception.EnforcerException: Error while parsing JWT
enforcer_1  | 	at org.wso2.choreo.connect.enforcer.security.jwt.validator.JWTValidator.validateToken(JWTValidator.java:110) ~[org.wso2.choreo.connect.enforcer-1.0.0.jar:1.0.0]
enforcer_1  | 	at org.wso2.choreo.connect.enforcer.security.jwt.validator.JWTValidator.validateJWTToken(JWTValidator.java:74) ~[org.wso2.choreo.connect.enforcer-1.0.0.jar:1.0.0]
enforcer_1  | 	at org.wso2.choreo.connect.enforcer.security.jwt.JWTAuthenticator.getJwtValidationInfo(JWTAuthenticator.java:559) [org.wso2.choreo.connect.enforcer-1.0.0.jar:1.0.0]
enforcer_1  | 	at org.wso2.choreo.connect.enforcer.security.jwt.JWTAuthenticator.authenticate(JWTAuthenticator.java:186) [org.wso2.choreo.connect.enforcer-1.0.0.jar:1.0.0]
enforcer_1  | 	at org.wso2.choreo.connect.enforcer.security.AuthFilter.authenticate(AuthFilter.java:159) [org.wso2.choreo.connect.enforcer-1.0.0.jar:1.0.0]
enforcer_1  | 	at org.wso2.choreo.connect.enforcer.security.AuthFilter.handleRequest(AuthFilter.java:138) [org.wso2.choreo.connect.enforcer-1.0.0.jar:1.0.0]
enforcer_1  | 	at org.wso2.choreo.connect.enforcer.api.API.executeFilterChain(API.java:42) [org.wso2.choreo.connect.enforcer-1.0.0.jar:1.0.0]
enforcer_1  | 	at org.wso2.choreo.connect.enforcer.api.RestAPI.process(RestAPI.java:165) [org.wso2.choreo.connect.enforcer-1.0.0.jar:1.0.0]
enforcer_1  | 	at org.wso2.choreo.connect.enforcer.server.HttpRequestHandler.process(HttpRequestHandler.java:57) [org.wso2.choreo.connect.enforcer-1.0.0.jar:1.0.0]
enforcer_1  | 	at org.wso2.choreo.connect.enforcer.grpc.ExtAuthService.check(ExtAuthService.java:79) [org.wso2.choreo.connect.enforcer-1.0.0.jar:1.0.0]
enforcer_1  | 	at io.envoyproxy.envoy.service.auth.v3.AuthorizationGrpc$MethodHandlers.invoke(AuthorizationGrpc.java:245) [org.wso2.choreo.connect.enforcer-1.0.0.jar:1.0.0]
enforcer_1  | 	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:180) [org.wso2.choreo.connect.enforcer-1.0.0.jar:1.0.0]
enforcer_1  | 	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35) [org.wso2.choreo.connect.enforcer-1.0.0.jar:1.0.0]
enforcer_1  | 	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23) [org.wso2.choreo.connect.enforcer-1.0.0.jar:1.0.0]
enforcer_1  | 	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40) [org.wso2.choreo.connect.enforcer-1.0.0.jar:1.0.0]
enforcer_1  | 	at io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86) [org.wso2.choreo.connect.enforcer-1.0.0.jar:1.0.0]
enforcer_1  | 	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331) [org.wso2.choreo.connect.enforcer-1.0.0.jar:1.0.0]
enforcer_1  | 	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:814) [org.wso2.choreo.connect.enforcer-1.0.0.jar:1.0.0]
enforcer_1  | 	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [org.wso2.choreo.connect.enforcer-1.0.0.jar:1.0.0]
enforcer_1  | 	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [org.wso2.choreo.connect.enforcer-1.0.0.jar:1.0.0]
enforcer_1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
enforcer_1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
enforcer_1  | 	at java.lang.Thread.run(Unknown Source) [?:?]
enforcer_1  | Caused by: org.wso2.carbon.apimgt.common.gateway.exception.JWTGeneratorException: Error while parsing JWT claims
enforcer_1  | 	at org.wso2.carbon.apimgt.common.gateway.jwttransformer.DefaultJWTTransformer.getTransformedConsumerKey(DefaultJWTTransformer.java:54) ~[org.wso2.choreo.connect.enforcer-1.0.0.jar:1.0.0]
enforcer_1  | 	at org.wso2.choreo.connect.enforcer.security.jwt.validator.JWTValidator.getConsumerKey(JWTValidator.java:169) ~[org.wso2.choreo.connect.enforcer-1.0.0.jar:1.0.0]
enforcer_1  | 	at org.wso2.choreo.connect.enforcer.security.jwt.validator.JWTValidator.validateToken(JWTValidator.java:92) ~[org.wso2.choreo.connect.enforcer-1.0.0.jar:1.0.0]
enforcer_1  | 	... 22 more
enforcer_1  | Caused by: java.text.ParseException: The "aud" claim is not a String
enforcer_1  | 	at com.nimbusds.jwt.JWTClaimsSet.getStringClaim(JWTClaimsSet.java:485) ~[org.wso2.choreo.connect.enforcer-1.0.0.jar:1.0.0]
enforcer_1  | 	at org.wso2.carbon.apimgt.common.gateway.jwttransformer.DefaultJWTTransformer.getTransformedConsumerKey(DefaultJWTTransformer.java:50) ~[org.wso2.choreo.connect.enforcer-1.0.0.jar:1.0.0]
enforcer_1  | 	at org.wso2.choreo.connect.enforcer.security.jwt.validator.JWTValidator.getConsumerKey(JWTValidator.java:169) ~[org.wso2.choreo.connect.enforcer-1.0.0.jar:1.0.0]
enforcer_1  | 	at org.wso2.choreo.connect.enforcer.security.jwt.validator.JWTValidator.validateToken(JWTValidator.java:92) ~[org.wso2.choreo.connect.enforcer-1.0.0.jar:1.0.0]
enforcer_1  | 	... 22 more
enforcer_1  | [2023-02-07 13:54:29,240][6ec8ae0d-17d2-40f7-b8fc-af3b5a64050e] ERROR - {org.wso2.choreo.connect.enforcer.security.AuthFilter} - None of the authenticators were able to authenticate the request: /test/1.0.0
```

**Comment by pubudu538** [comment]
Duplicate git issue - https://github.com/wso2/product-microgateway/issues/3248
