### ISSUE TITLE
Micro gateway restarting in PROD

### ISSUE THREAD

**Issue by vikumkbv** [wso2/product-microgateway#3321]
### Problem

MGW keep restarting with the following error

The issue is with Microgateway runtime 3.2.0
Java version : 11.0.16.0.1
MGW toolkit version : 3.2.0 (u2 level 40)

MGW runtime is keep restarting after it received nullPointException and also after this NPE all the requests are responded with 408 HTTP status code even for the health check call. We were able to observe following error messages from the log file.

```
2023-03-15 01:56:22,215 WARN [org.ballerinalang.net.http.BallerinaHTTPConnectorListener] - [BallerinaHTTPConnectorListener] [] Error in HTTP server connector: Remote client closed the connection before initiating outbound response
```

```
[2023-03-15 13:07:44,673] SEVERE {b7a.log.crash} - null
java.lang.NullPointerException
    	at org.ballerinalang.jvm.BallerinaErrors.filterStackTraceElement(BallerinaErrors.java:255)
    	at org.ballerinalang.jvm.values.ErrorValue.getStackTrace(ErrorValue.java:192)
    	at org.ballerinalang.jvm.values.ErrorValue.getPrintableStackTrace(ErrorValue.java:208)
    	at org.ballerinalang.net.http.HttpUtil.handleFailure(HttpUtil.java:415)
    	at org.ballerinalang.net.http.HttpCallableUnitCallback.notifyFailure(HttpCallableUnitCallback.java:42)
    	at org.ballerinalang.jvm.scheduling.Scheduler.postProcess(Scheduler.java:324)
    	at org.ballerinalang.jvm.scheduling.Scheduler.run(Unknown Source)
    	at org.ballerinalang.jvm.scheduling.Scheduler.runSafely(Unknown Source)
    	at java.base/java.lang.Thread.run(Unknown Source)
```

### Solution

N/A

**Comment by npamudika** [comment]
Fixed by https://github.com/wso2/product-microgateway/pull/3323
