### ISSUE TITLE
[dev-first] API level interceptors gives error

### ISSUE THREAD

**Issue by Rajith90** [wso2/product-microgateway#450]
**Description:**
When I define API level interceptors it gives an error while build command

**Suggested Assignees:**

**Affected Product Version:**
3.0.0-alpha
**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
1. Define a definition yaml like for swagger petstore yaml
`apis:
    /petstore/v1:
        title: Swagger Petstore
        version: 1.0.0
        production_endpoint:
            type: 'http'
            urls: 
                - 'https://petstore.swagger.io/v2'
        sandbox_endpoint:
            type: 'http'
            urls: 
                - 'https://sand.petstore.ballerina.io/'
        request_interceptor: validateRequest
        response_interceptor: validateResponse
        resources:
            /pet/findByStatus:
                get:
                    production_endpoint:
                        type: 'http'
                        urls: 
                            - 'http://www.mocky.io/v2/5cbd4d1d2f0000e70a16cc0e'
                    throttle_policy: 3PerMin
                    
        

        `
2. Then it gives the following error when building 
`[2019-04-23 11:02:11,227] ERROR {org.wso2.apimgt.gateway.cli.cmd.Main} - Error while reading the definitions.yaml 
org.wso2.apimgt.gateway.cli.exception.CLIRuntimeException: Error while reading the definitions.yaml
	at org.wso2.apimgt.gateway.cli.utils.MgwDefinitionUtils.setMgwDefinition(MgwDefinitionUtils.java:47)
	at org.wso2.apimgt.gateway.cli.cmd.BuildCmd.execute(BuildCmd.java:102)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.wso2.apimgt.gateway.cli.cmd.Main.main(Main.java:51)
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "request_interceptor" (class org.wso2.apimgt.gateway.cli.model.mgwdefinition.MgwAPIDefinition), not marked as ignorable (9 known properties: "security", "resources", "request-interceptor", "title", "response-interceptor", "production_endpoint", "sandbox_endpoint", "version", "cors"])
 at [Source: (File); line: 13, column: 45] (through reference chain: org.wso2.apimgt.gateway.cli.model.mgwdefinition.MgwRootDefinition["apis"]->org.wso2.apimgt.gateway.cli.model.mgwdefinition.MgwAPIsDefinition["/petstore/v1"]->org.wso2.apimgt.gateway.cli.model.mgwdefinition.MgwAPIDefinition["request_interceptor"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:60)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:822)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1151)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1567)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1545)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:293)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.SettableAnyProperty.deserialize(SettableAnyProperty.java:154)
	at com.fasterxml.jackson.databind.deser.SettableAnyProperty.deserializeAndSet(SettableAnyProperty.java:134)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1539)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:293)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:287)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4001)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2890)
	at org.wso2.apimgt.gateway.cli.utils.MgwDefinitionUtils.setMgwDefinition(MgwDefinitionUtils.java:44)
	... 3 more`

**Related Issues:**

**Comment by hasuniea** [comment]
fixes https://github.com/wso2/product-microgateway/pull/458
