### ISSUE TITLE
Null values published for 'apiName' and 'destination' attrs

### ISSUE THREAD

**Issue by praminda** [wso2/product-microgateway#558]
**Description:**
Below error is logged in wso2am-analytics-2.6.0 when processing MGW published stats.
```
osgi> [2019-05-23 16:07:37,782]  INFO {org.wso2.analytics.apim.rest.api.file.impl.UsageApiServiceImpl} - Successfully uploaded the API Usage file [api-usage-data.dat.1558607852312.bffb34ac-e3bc-4da8-b2af-4b3723c49360.zip]
[2019-05-23 16:08:21,726]  INFO {org.wso2.extension.siddhi.io.mgwfile.MGWFileDataRetriever} - Started publishing API usage in file : [ FileName : api-usage-data.dat.1558607852312.bffb34ac-e3bc-4da8-b2af-4b3723c49360.zip, TimeStamp : 1558607852000]
[2019-05-23 16:08:21,789]  INFO {org.wso2.extension.siddhi.io.mgwfile.MGWFileDataRetriever} - Completed publishing API Usage from file : [ FileName : api-usage-data.dat.1558607852312.bffb34ac-e3bc-4da8-b2af-4b3723c49360.zip, TimeStamp : 1558607852000]
[2019-05-23 16:08:22,007] ERROR {org.wso2.siddhi.core.aggregation.IncrementalExecutor} - Exception occurred when writing to aggregation table of duration 'SECONDS'. This should be investigated as this can cause accuracy loss. org.wso2.extension.siddhi.store.rdbms.exception.RDBMSTableException: Error in adding events to 'ApiPerDestinationAgg_SECONDS' store: Column 'destination' cannot be null
	at org.wso2.extension.siddhi.store.rdbms.RDBMSEventTable.add(RDBMSEventTable.java:562)
	at org.wso2.siddhi.core.table.record.AbstractRecordTable.add(AbstractRecordTable.java:98)
	at org.wso2.siddhi.core.table.Table.addEvents(Table.java:139)
	at org.wso2.siddhi.core.aggregation.IncrementalExecutor.lambda$dispatchEvents$2(IncrementalExecutor.java:269)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
...
```
<details>
<summary>Complete log...</summary>

```
Caused by: java.sql.BatchUpdateException: Column 'destination' cannot be null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createBatchUpdateException(SQLError.java:1163)
	at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1823)
	at com.mysql.jdbc.PreparedStatement.executeBatchInternal(PreparedStatement.java:1307)
	at com.mysql.jdbc.StatementImpl.executeBatch(StatementImpl.java:970)
	at com.zaxxer.hikari.proxy.StatementProxy.executeBatch(StatementProxy.java:127)
	at com.zaxxer.hikari.proxy.HikariPreparedStatementProxy.executeBatch(HikariPreparedStatementProxy.java)
	at org.wso2.extension.siddhi.store.rdbms.RDBMSEventTable.batchExecuteQueriesWithRecords(RDBMSEventTable.java:1418)
	at org.wso2.extension.siddhi.store.rdbms.RDBMSEventTable.add(RDBMSEventTable.java:559)
	... 6 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Column 'destination' cannot be null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2495)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1903)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2124)
	at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1801)
	... 12 more

[2019-05-23 16:08:22,008] ERROR {org.wso2.siddhi.core.aggregation.IncrementalExecutor} - Exception occurred when writing to aggregation table of duration 'SECONDS'. This should be investigated as this can cause accuracy loss. org.wso2.extension.siddhi.store.rdbms.exception.RDBMSTableException: Error in adding events to 'APIM_ReqCountAgg_SECONDS' store: Column 'apiName' cannot be null
	at org.wso2.extension.siddhi.store.rdbms.RDBMSEventTable.add(RDBMSEventTable.java:562)
	at org.wso2.siddhi.core.table.record.AbstractRecordTable.add(AbstractRecordTable.java:98)
	at org.wso2.siddhi.core.table.Table.addEvents(Table.java:139)
	at org.wso2.siddhi.core.aggregation.IncrementalExecutor.lambda$dispatchEvents$2(IncrementalExecutor.java:269)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.BatchUpdateException: Column 'apiName' cannot be null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createBatchUpdateException(SQLError.java:1163)
	at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1823)
	at com.mysql.jdbc.PreparedStatement.executeBatchInternal(PreparedStatement.java:1307)
	at com.mysql.jdbc.StatementImpl.executeBatch(StatementImpl.java:970)
	at com.zaxxer.hikari.proxy.StatementProxy.executeBatch(StatementProxy.java:127)
	at com.zaxxer.hikari.proxy.HikariPreparedStatementProxy.executeBatch(HikariPreparedStatementProxy.java)
	at org.wso2.extension.siddhi.store.rdbms.RDBMSEventTable.batchExecuteQueriesWithRecords(RDBMSEventTable.java:1418)
	at org.wso2.extension.siddhi.store.rdbms.RDBMSEventTable.add(RDBMSEventTable.java:559)
	... 6 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Column 'apiName' cannot be null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2495)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1903)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2124)
	at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1801)
	... 12 more
```
</details>

**OS, DB, other environment details and versions:**    
WSO2 APIM 2.6.0 with APIM Analytics 2.6.0

**Steps to reproduce:**
- Configure WSO2 APIM analytics 2.6.0 with MGW
- Build a MGW project
- Send some requests

**Comment by praminda** [comment]
#574 will fix the issue. However to see the analytics for dev first APIs in APIM side, user first need create a similar API in API Publisher. (same `apiName` and `apiContext`)
