### ISSUE TITLE
An Exception occurred java.nio.channels.ClosedChannelException while running the testcases

### ISSUE THREAD

**Issue by hasuniea** [wso2/product-microgateway#978]
### Description:
Getting an issue while running the tests.
2020-02-07 14:12:39 WARN  ChannelInitializer:151 - Failed to initialize a channel. Closing: [id: 0xce595933]
java.lang.RuntimeException: ALPN unsupported. Is your classpath configured correctly? For Conscrypt, add the appropriate Conscrypt JAR to classpath and set the security provider. For Jetty-ALPN, see http://www.eclipse.org/jetty/documentation/current/alpn-chapter.html#alpn-starting
	at io.netty.handler.ssl.JdkAlpnApplicationProtocolNegotiator$FailureWrapper.wrapSslEngine(JdkAlpnApplicationProtocolNegotiator.java:122)
	at io.netty.handler.ssl.JdkSslContext.configureAndWrapEngine(JdkSslContext.java:245)
	at io.netty.handler.ssl.JdkSslContext.newEngine(JdkSslContext.java:215)
	at io.netty.handler.ssl.SslContext.newHandler(SslContext.java:913)
	at io.netty.handler.ssl.SslContext.newHandler(SslContext.java:905)
	at org.wso2.micro.gateway.tests.util.HTTP2Client.Http2ClientInitializer.configureSsl(Http2ClientInitializer.java:105)
	at org.wso2.micro.gateway.tests.util.HTTP2Client.Http2ClientInitializer.initChannel(Http2ClientInitializer.java:82)
	at org.wso2.micro.gateway.tests.util.HTTP2Client.Http2ClientInitializer.initChannel(Http2ClientInitializer.java:50)
	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:113)
	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:105)
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:606)
	at io.netty.channel.DefaultChannelPipeline.access$000(DefaultChannelPipeline.java:46)
	at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1412)
	at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1131)
	at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:656)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:510)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:423)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:482)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:745)
2020-02-07 14:12:39 ERROR Http2ClientRequest:192 - An Exception occurred java.nio.channels.ClosedChannelException

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by praminda** [comment]
@hasuniea @VirajSalaka Do we have any update on this? I believe this is due to JDK/http2 compatibility. Did we made any progress on this with the recent changes?

**Comment by Rajith90** [comment]
@VirajSalaka
